export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// SEARCH WIDGET
export const SET_QUERY = "SET_QUERY";
export const SAVE_QUERY = "SAVE_QUERY";
export const SEARCH_LOADING = "SEARCH_LOADING";

// PROFILE TYPES
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE"; // clear profile after logging out
export const GET_PROFILES = "GET_PROFILES";
export const GET_HISTORY = "GET_HISTORY";

// LANDING TYPES
export const GET_LANDING_DATA = "GET_LANDING_DATA";
export const SET_LANDING_STATUS = "SET_LANDING_STATUS";

export const GET_DELIVERY = "GET_DELIVERY";

// SEARCH RESULT TYPES
export const SEARCH_RESULT_OVERVIEW = "SEARCH_RESULT_OVERVIEW";
export const GET_INDIVIDUAL_HOTEL = "GET_INDIVIDUAL_HOTEL";

// BOOKING/PAYMENT/CONFIRMATION
export const SET_BOOKING = "SET_BOOKING";
export const SAVE_BOOKING = "SAVE_BOOKING";
export const CLEAR_BOOKING = "CLEAR_BOOKING";
export const CHANGE_RESERVATION = "CHANGE_RESERVATION";
