export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// SEARCH WIDGET
export const SET_QUERY = "SET_QUERY";
export const SAVE_QUERY = "SAVE_QUERY";

// PROFILE TYPES
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE"; // clear profile after logging out
export const GET_PROFILES = "GET_PROFILES";

// LANDING TYPES
export const GET_LANDING_DATA = "GET_LANDING_DATA";

export const GET_DELIVERY = "GET_DELIVERY";

// SEARCH RESULT TYPES
export const SEARCH_RESULT_OVERVIEW = "SEARCH_RESULT_OVERVIEW";
export const GET_INDIVIDUAL_HOTEL = "GET_INDIVIDUAL_HOTEL";
