export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_QUERY = "SET_QUERY";

// PROFILE TYPES
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE"; // clear profile after logging out
export const GET_PROFILES = "GET_PROFILES";

export const GET_CATEGORY = "GET_CATEGORY";

// PRODUCT TYPES
export const GET_PRODUCT = "GET_PRODUCT";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const CLEAR_CURRENT_PRODUCT = "CLEAR_CURRENT_PRODUCT";
